import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DatabaseService } from './database.service';
import { SeederService } from './seeds/seeder.service';
import {
  User,
  UserSession,
  OtpVerification,
  EmailOtp,
  Role,
  State,
  LocalGovernmentArea,
  Ward,
  Neighborhood,
  Landmark,
  UserLocation,
  Post,
  PostComment,
  PostMedia,
  PostReaction,
  PostCategory,
  UserNeighborhood,
  Media,
  CommentMedia,
  Listing,
  ListingCategory,
  ListingMedia,
  ListingSave,
  EventCategory,
  Event,
  EventMedia,
  EventAttendee,
  UserBookmark,
  UserDashboardStats,
  NinVerification,
  IdentityDocument,
  VerificationAudit,
  UserBadge,
  CommunityEndorsement,
  Achievement,
  UserAchievement,
  Badge,
  GamificationBadge,
  UserActivityLog,
  UserPoints,
  LeaderboardSnapshot,
  BusinessProfile,
  BusinessCategory,
  BusinessLicense,
  BusinessService,
  BusinessReview,
  BusinessInquiry,
  ServiceInquiry,
  BusinessActivityLog,
  NigerianState,
  NigerianLanguage,
  CulturalBackground,
  ProfessionalCategory,
  UserLanguage,
  UserPrivacySettings,
} from './entities';
// Import messaging entities from the messaging service
import { Conversation } from '../../../apps/messaging-service/src/entities/conversation.entity';
import { ConversationParticipant } from '../../../apps/messaging-service/src/entities/conversation-participant.entity';
import { Message } from '../../../apps/messaging-service/src/entities/message.entity';
import { MessageReceipt } from '../../../apps/messaging-service/src/entities/message-receipt.entity';
import { TypingIndicator } from '../../../apps/messaging-service/src/entities/typing-indicator.entity';

@Module({
  imports: [
    ConfigModule,
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        host: configService.get('DATABASE_HOST', 'localhost'),
        port: configService.get('DATABASE_PORT', 5432),
        username: configService.get('DATABASE_USERNAME', 'mecabal'),
        password: configService.get('DATABASE_PASSWORD', 'mecabal_password'),
        database: configService.get('DATABASE_NAME', 'mecabal_prod'),
        entities: [
          User,
          UserSession,
          OtpVerification,
          EmailOtp,
          Role,
          State,
          LocalGovernmentArea,
          Ward,
          Neighborhood,
          Landmark,
          UserLocation,
          Post,
          PostComment,
          PostMedia,
          PostReaction,
          PostCategory,
          UserNeighborhood,
          Media,
          CommentMedia,
          Listing,
          ListingCategory,
          ListingMedia,
          ListingSave,
          EventCategory,
          Event,
          EventMedia,
          EventAttendee,
          UserBookmark,
          UserDashboardStats,
          NinVerification,
          IdentityDocument,
          VerificationAudit,
          UserBadge,
          CommunityEndorsement,
          Achievement,
          UserAchievement,
          Badge,
          GamificationBadge,
          UserActivityLog,
          UserPoints,
          LeaderboardSnapshot,
          BusinessProfile,
          BusinessCategory,
          BusinessLicense,
          BusinessService,
          BusinessReview,
          BusinessInquiry,
          BusinessActivityLog,
          NigerianState,
          NigerianLanguage,
          CulturalBackground,
          ProfessionalCategory,
          UserLanguage,
          UserPrivacySettings,
          // Messaging entities
          Conversation,
          ConversationParticipant,
          Message,
          MessageReceipt,
          TypingIndicator,
        ],
        synchronize: configService.get('DATABASE_SYNCHRONIZE') === 'true', // Use env variable for initial deployment
        logging: configService.get('NODE_ENV') === 'development',
        ssl: configService.get('DATABASE_SSL') === 'true' ? {
          rejectUnauthorized: false,
        } : false,
        // Enable PostGIS support
        extra: {
          application_name: 'mecabal-backend',
        },
      }),
      inject: [ConfigService],
    }),
    TypeOrmModule.forFeature([
      User,
      UserSession,
      OtpVerification,
      EmailOtp,
      Role,
      State,
      LocalGovernmentArea,
      Ward,
      Neighborhood,
      Landmark,
      UserLocation,
      Post,
      PostComment,
      PostMedia,
      PostReaction,
      PostCategory,
      UserNeighborhood,
      Media,
      CommentMedia,
      Listing,
      ListingCategory,
      ListingMedia,
      ListingSave,
      EventCategory,
      Event,
      EventMedia,
      EventAttendee,
      UserBookmark,
      UserDashboardStats,
      NinVerification,
      IdentityDocument,
      VerificationAudit,
      UserBadge,
      CommunityEndorsement,
      Achievement,
      UserAchievement,
      Badge,
      GamificationBadge,
      UserActivityLog,
      UserPoints,
      LeaderboardSnapshot,
      BusinessProfile,
      BusinessCategory,
      BusinessLicense,
      BusinessService,
      BusinessReview,
      BusinessInquiry,
      ServiceInquiry,
      BusinessActivityLog,
      NigerianState,
      NigerianLanguage,
      CulturalBackground,
      ProfessionalCategory,
      UserLanguage,
      UserPrivacySettings,
      // Messaging entities
      Conversation,
      ConversationParticipant,
      Message,
      MessageReceipt,
      TypingIndicator,
    ]),
  ],
  providers: [DatabaseService, SeederService],
  exports: [DatabaseService, TypeOrmModule, SeederService],
})
export class DatabaseModule {}
