module.exports = {
  apps: [
    {
      name: 'api-gateway',
      script: 'dist/apps/api-gateway/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      max_memory_restart: '300M',
      error_file: 'logs/api-gateway-error.log',
      out_file: 'logs/api-gateway-out.log',
      time: true,
    },
    {
      name: 'auth-service',
      script: 'dist/apps/auth-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      max_memory_restart: '300M',
      error_file: 'logs/auth-service-error.log',
      out_file: 'logs/auth-service-out.log',
      time: true,
    },
    {
      name: 'user-service',
      script: 'dist/apps/user-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      max_memory_restart: '300M',
      error_file: 'logs/user-service-error.log',
      out_file: 'logs/user-service-out.log',
      time: true,
    },
    {
      name: 'social-service',
      script: 'dist/apps/social-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      max_memory_restart: '200M',
      error_file: 'logs/social-service-error.log',
      out_file: 'logs/social-service-out.log',
      time: true,
    },
    {
      name: 'messaging-service',
      script: 'dist/apps/messaging-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      max_memory_restart: '250M',
      error_file: 'logs/messaging-service-error.log',
      out_file: 'logs/messaging-service-out.log',
      time: true,
    },
    {
      name: 'marketplace-service',
      script: 'dist/apps/marketplace-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      max_memory_restart: '250M',
      error_file: 'logs/marketplace-service-error.log',
      out_file: 'logs/marketplace-service-out.log',
      time: true,
    },
    {
      name: 'events-service',
      script: 'dist/apps/events-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
      },
      max_memory_restart: '250M',
      error_file: 'logs/events-service-error.log',
      out_file: 'logs/events-service-out.log',
      time: true,
    },
    {
      name: 'notification-service',
      script: 'dist/apps/notification-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3007,
      },
      max_memory_restart: '200M',
      error_file: 'logs/notification-service-error.log',
      out_file: 'logs/notification-service-out.log',
      time: true,
    },
    {
      name: 'location-service',
      script: 'dist/apps/location-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3008,
        LOCATION_SERVICE_PORT: 3008,
      },
      max_memory_restart: '250M',
      error_file: 'logs/location-service-error.log',
      out_file: 'logs/location-service-out.log',
      time: true,
    },
    {
      name: 'business-service',
      script: 'dist/apps/business-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3009,
      },
      max_memory_restart: '250M',
      error_file: 'logs/business-service-error.log',
      out_file: 'logs/business-service-out.log',
      time: true,
    },
  ],
};
