import { BusinessCategory } from '../entities/business-category.entity';

export const businessCategoriesData: Partial<BusinessCategory>[] = [
  {
    id: 'household-services',
    name: 'Household Services',
    description: 'Home maintenance and household help',
    icon: 'home-repair',
    color: '#4CAF50',
    subcategories: [
      'Cleaning',
      'Plumbing',
      'Electrical',
      'Carpentry',
      'Painting',
      'Gardening',
      'Pest Control',
      'Air Conditioning',
      'Generator Repair',
      'Security Installation',
      'Laundry Services',
      'Home Appliance Repair',
      'Roofing',
      'Tiling',
      'Fumigation',
    ],
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    description: 'Professional and business services',
    icon: 'briefcase',
    color: '#2196F3',
    subcategories: [
      'Legal Services',
      'Accounting',
      'Tax Consulting',
      'Real Estate',
      'Insurance',
      'Business Consulting',
      'IT Services',
      'Web Development',
      'Graphic Design',
      'Photography',
      'Videography',
      'Event Planning',
      'Marketing',
      'Translation',
      'Writing Services',
    ],
  },
  {
    id: 'health-wellness',
    name: 'Health & Wellness',
    description: 'Healthcare and wellness services',
    icon: 'medical-services',
    color: '#E91E63',
    subcategories: [
      'Home Nursing',
      'Physiotherapy',
      'Massage Therapy',
      'Personal Training',
      'Nutrition Consulting',
      'Mental Health',
      'Dental Services',
      'Optometry',
      'Pharmacy',
      'Medical Labs',
      'Fitness Training',
      'Yoga Instruction',
    ],
  },
  {
    id: 'education-tutoring',
    name: 'Education & Tutoring',
    description: 'Educational and training services',
    icon: 'school',
    color: '#FF9800',
    subcategories: [
      'Home Tutoring',
      'Language Classes',
      'Music Lessons',
      'Art Classes',
      'Coding Classes',
      'Exam Preparation',
      'Vocational Training',
      'Special Needs Education',
      'Early Childhood Education',
      'Adult Education',
    ],
  },
  {
    id: 'food-catering',
    name: 'Food & Catering',
    description: 'Food services and catering',
    icon: 'restaurant',
    color: '#F44336',
    subcategories: [
      'Home Catering',
      'Small Chops',
      'Baked Goods',
      'Meal Prep',
      'Food Delivery',
      'Event Catering',
      'Restaurant',
      'Food Truck',
    ],
  },
  {
    id: 'beauty-personal-care',
    name: 'Beauty & Personal Care',
    description: 'Beauty and grooming services',
    icon: 'face',
    color: '#9C27B0',
    subcategories: [
      'Hair Styling',
      'Barbing',
      'Makeup Artistry',
      'Nail Services',
      'Spa Services',
      'Beauty Therapy',
      'Skincare',
      'Lash Extensions',
    ],
  },
  {
    id: 'automotive',
    name: 'Automotive',
    description: 'Car services and repairs',
    icon: 'directions-car',
    color: '#607D8B',
    subcategories: [
      'Auto Mechanic',
      'Car Wash',
      'Auto Electrical',
      'Tire Services',
      'Car AC Repair',
      'Panel Beating',
      'Car Detailing',
      'Towing Services',
    ],
  },
  {
    id: 'transportation',
    name: 'Transportation',
    description: 'Transport and logistics',
    icon: 'local-shipping',
    color: '#795548',
    subcategories: [
      'Courier Services',
      'Moving Services',
      'Taxi/Ride Services',
      'Logistics',
      'Delivery Services',
    ],
  },
  {
    id: 'childcare',
    name: 'Childcare',
    description: 'Children and family services',
    icon: 'child-care',
    color: '#FFEB3B',
    subcategories: [
      'Babysitting',
      'Daycare',
      'Nanny Services',
      'After School Care',
      'Child Tutoring',
    ],
  },
  {
    id: 'pet-care',
    name: 'Pet Care',
    description: 'Pet services and care',
    icon: 'pets',
    color: '#8BC34A',
    subcategories: [
      'Pet Grooming',
      'Veterinary',
      'Dog Walking',
      'Pet Sitting',
      'Pet Training',
    ],
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    description: 'Entertainment and recreation',
    icon: 'music-note',
    color: '#00BCD4',
    subcategories: [
      'DJ Services',
      'MC Services',
      'Live Band',
      'Comedy',
      'Magic Shows',
      'Equipment Rental',
    ],
  },
  {
    id: 'fashion-tailoring',
    name: 'Fashion & Tailoring',
    description: 'Fashion and clothing services',
    icon: 'checkroom',
    color: '#E91E63',
    subcategories: [
      'Tailoring',
      'Fashion Design',
      'Alterations',
      'Dry Cleaning',
      'Shoe Repair',
    ],
  },
  {
    id: 'technology',
    name: 'Technology',
    description: 'Tech services and repairs',
    icon: 'computer',
    color: '#3F51B5',
    subcategories: [
      'Phone Repair',
      'Computer Repair',
      'Software Installation',
      'Data Recovery',
      'CCTV Installation',
      'Smart Home Setup',
    ],
  },
  {
    id: 'agriculture',
    name: 'Agriculture',
    description: 'Agricultural services',
    icon: 'agriculture',
    color: '#4CAF50',
    subcategories: [
      'Farming Services',
      'Poultry',
      'Fishery',
      'Livestock',
      'Agro-Processing',
    ],
  },
  {
    id: 'construction',
    name: 'Construction',
    description: 'Construction and building',
    icon: 'construction',
    color: '#FF5722',
    subcategories: [
      'Building Construction',
      'Renovation',
      'Architectural Design',
      'Surveying',
      'Civil Engineering',
      'Interior Design',
    ],
  },
];

export async function seedBusinessCategories(dataSource: any) {
  const categoryRepo = dataSource.getRepository(BusinessCategory);

  for (const categoryData of businessCategoriesData) {
    const existing = await categoryRepo.findOne({
      where: { id: categoryData.id },
    });

    if (!existing) {
      const category = categoryRepo.create(categoryData);
      await categoryRepo.save(category);
      console.log(`✅ Created business category: ${categoryData.name}`);
    }
  }
}
