import {
  NigerianState,
  NigerianLanguage,
  CulturalBackground,
  ProfessionalCategory,
} from '../entities';

export const NIGERIAN_STATES_SEED: Partial<NigerianState>[] = [
  {
    id: 'lagos',
    name: 'Lagos',
    region: 'South West',
    capital: 'Ikeja',
    lgas: [
      'Ikeja', 'Surulere', 'Alimosho', 'Lagos Island', 'Lagos Mainland',
      'Eti-Osa', 'Ikorodu', 'Epe', 'Badagry', 'Ibeju-Lekki',
      'Apapa', 'Ifako-Ijaiye', 'Mushin', 'Oshodi-Isolo', 'Ojo',
      'Kosofe', 'Shomolu', 'Ajeromi-Ifelodun', 'Amuwo-Odofin', 'Lagos Island'
    ],
    population: 14862000,
    areaSqKm: 3577,
  },
  {
    id: 'kano',
    name: 'Kano',
    region: 'North West',
    capital: 'Kano',
    lgas: [
      'Kano Municipal', 'Dala', 'Gwale', 'Fagge', 'Nassarawa',
      'Tarauni', 'Ungogo', 'Kumbotso', 'Dawakin Tofa', 'Tofa',
      'Rimin Gado', 'Bagwai', 'Gezawa', 'Gabasawa', 'Minjibir',
      'Dambatta', 'Makoda', 'Gwarzo', 'Karaye', 'Rogo',
      'Kabo', 'Bunkure', 'Kibiya', 'Rano', 'Bebeji',
      'Kiru', 'Sumaila', 'Garko', 'Warawa', 'Garun Mallam',
      'Wudil', 'Takai', 'Albasu', 'Gaya', 'Ajingi',
      'Tudun Wada', 'Doguwa', 'Tsanyawa', 'Shanono', 'Gezawa',
      'Madobi', 'Kura', 'Bichi', 'Tsanyawa', 'Gwarzo'
    ],
    population: 13076892,
    areaSqKm: 20131,
  },
  {
    id: 'rivers',
    name: 'Rivers',
    region: 'South South',
    capital: 'Port Harcourt',
    lgas: [
      'Port Harcourt', 'Obio-Akpor', 'Okrika', 'Ogu-Bolo', 'Eleme',
      'Tai', 'Gokana', 'Khana', 'Oyigbo', 'Opobo-Nkoro',
      'Andoni', 'Bonny', 'Degema', 'Asari-Toru', 'Akuku-Toru',
      'Abua-Odual', 'Ahoada West', 'Ahoada East', 'Ogba-Egbema-Ndoni',
      'Ikwerre', 'Emohua', 'Omuma', 'Etche', 'Okehi'
    ],
    population: 5195000,
    areaSqKm: 11077,
  },
  {
    id: 'kaduna',
    name: 'Kaduna',
    region: 'North West',
    capital: 'Kaduna',
    lgas: [
      'Kaduna North', 'Kaduna South', 'Igabi', 'Ikara', 'Jaba',
      'Jema\'a', 'Kachia', 'Kaduna North', 'Kaduna South', 'Kagarko',
      'Kajuru', 'Kaura', 'Kauru', 'Kubau', 'Kudan',
      'Lere', 'Makarfi', 'Sabon Gari', 'Sanga', 'Soba',
      'Zangon Kataf', 'Chikun', 'Giwa', 'Kaduna North', 'Kaduna South'
    ],
    population: 8250000,
    areaSqKm: 46053,
  },
  {
    id: 'oyo',
    name: 'Oyo',
    region: 'South West',
    capital: 'Ibadan',
    lgas: [
      'Ibadan North', 'Ibadan North-East', 'Ibadan North-West', 'Ibadan South-East', 'Ibadan South-West',
      'Akinyele', 'Egbeda', 'Ido', 'Lagelu', 'Ona Ara',
      'Oluyole', 'Afijio', 'Atiba', 'Atisbo', 'Saki East',
      'Saki West', 'Itesiwaju', 'Iwajowa', 'Kajola', 'Ogo Oluwa',
      'Ogbomoso North', 'Ogbomoso South', 'Olorunsogo', 'Ori Ire', 'Oyo',
      'Oyo East', 'Surulere', 'Ibarapa Central', 'Ibarapa East', 'Ibarapa North',
      'Iseyin', 'Kajola', 'Ogo Oluwa', 'Olorunsogo', 'Ori Ire'
    ],
    population: 7000000,
    areaSqKm: 28454,
  },
  {
    id: 'enugu',
    name: 'Enugu',
    region: 'South East',
    capital: 'Enugu',
    lgas: [
      'Enugu East', 'Enugu North', 'Enugu South', 'Aninri', 'Awgu',
      'Ezeagu', 'Igbo Etiti', 'Igbo Eze North', 'Igbo Eze South', 'Isi Uzo',
      'Nkanu East', 'Nkanu West', 'Nsukka', 'Oji River', 'Udenu',
      'Udi', 'Uzo Uwani'
    ],
    population: 4200000,
    areaSqKm: 7161,
  },
  {
    id: 'delta',
    name: 'Delta',
    region: 'South South',
    capital: 'Asaba',
    lgas: [
      'Aniocha North', 'Aniocha South', 'Bomadi', 'Burutu', 'Ethiope East',
      'Ethiope West', 'Ika North East', 'Ika South', 'Isoko North', 'Isoko South',
      'Ndokwa East', 'Ndokwa West', 'Okpe', 'Oshimili North', 'Oshimili South',
      'Patani', 'Sapele', 'Udu', 'Ughelli North', 'Ughelli South',
      'Ukwuani', 'Uvwie', 'Warri North', 'Warri South', 'Warri South West'
    ],
    population: 5500000,
    areaSqKm: 17698,
  },
  {
    id: 'abia',
    name: 'Abia',
    region: 'South East',
    capital: 'Umuahia',
    lgas: [
      'Aba North', 'Aba South', 'Arochukwu', 'Bende', 'Ikwuano',
      'Isiala Ngwa North', 'Isiala Ngwa South', 'Isuikwuato', 'Obi Ngwa', 'Ohafia',
      'Osisioma', 'Ugwunagbo', 'Ukwa East', 'Ukwa West', 'Umuahia North',
      'Umuahia South', 'Umu Nneochi'
    ],
    population: 3500000,
    areaSqKm: 6324,
  },
  {
    id: 'anambra',
    name: 'Anambra',
    region: 'South East',
    capital: 'Awka',
    lgas: [
      'Aguata', 'Anambra East', 'Anambra West', 'Anaocha', 'Awka North',
      'Awka South', 'Ayamelum', 'Dunukofia', 'Ekwusigo', 'Idemili North',
      'Idemili South', 'Ihiala', 'Njikoka', 'Nnewi North', 'Nnewi South',
      'Ogbaru', 'Onitsha North', 'Onitsha South', 'Orumba North', 'Orumba South',
      'Oyi'
    ],
    population: 5500000,
    areaSqKm: 4844,
  },
  {
    id: 'imo',
    name: 'Imo',
    region: 'South East',
    capital: 'Owerri',
    lgas: [
      'Aboh Mbaise', 'Ahiazu Mbaise', 'Ehime Mbano', 'Ezinihitte', 'Ideato North',
      'Ideato South', 'Ihitte/Uboma', 'Ikeduru', 'Isiala Mbano', 'Isu',
      'Mbaitoli', 'Ngor Okpala', 'Njaba', 'Nkwerre', 'Nwangele',
      'Obowo', 'Oguta', 'Ohaji/Egbema', 'Okigwe', 'Orlu',
      'Orsu', 'Oru East', 'Oru West', 'Owerri Municipal', 'Owerri North',
      'Owerri West', 'Unuimo'
    ],
    population: 4500000,
    areaSqKm: 5530,
  },
  {
    id: 'fct',
    name: 'Federal Capital Territory',
    region: 'North Central',
    capital: 'Abuja',
    lgas: [
      'Abaji', 'Gwagwalada', 'Kuje', 'Bwari', 'Kwali', 'Municipal Area Council'
    ],
    population: 3500000,
    areaSqKm: 1764,
  },
  // Additional States
  {
    id: 'abuja',
    name: 'Abuja',
    region: 'North Central',
    capital: 'Abuja',
    lgas: ['Municipal Area Council', 'Abaji', 'Gwagwalada', 'Kuje', 'Bwari', 'Kwali'],
    population: 3500000,
    areaSqKm: 1764,
  },
  {
    id: 'adamawa',
    name: 'Adamawa',
    region: 'North East',
    capital: 'Yola',
    lgas: ['Yola North', 'Yola South', 'Ganye', 'Toungo', 'Fufore', 'Girei', 'Hong', 'Maiha', 'Michika', 'Mubi North', 'Mubi South', 'Numan', 'Shelleng', 'Song', 'Toungo', 'Yola North', 'Yola South'],
    population: 4500000,
    areaSqKm: 36917,
  },
  {
    id: 'akwa-ibom',
    name: 'Akwa Ibom',
    region: 'South South',
    capital: 'Uyo',
    lgas: ['Uyo', 'Ikot Ekpene', 'Eket', 'Abak', 'Eastern Obolo', 'Eket', 'Esit Eket', 'Essien Udim', 'Etim Ekpo', 'Etinan', 'Ibeno', 'Ibesikpo Asutan', 'Ibiono-Ibom', 'Ika', 'Ikono', 'Ikot Abasi', 'Ini', 'Itu', 'Mbo', 'Mkpat-Enin', 'Nsit-Atai', 'Nsit-Ibom', 'Nsit-Ubium', 'Obot Akara', 'Okobo', 'Onna', 'Oron', 'Oruk Anam', 'Udung-Uko', 'Ukanafun', 'Uruan', 'Urue-Offong/Oruko', 'Uyo'],
    population: 5500000,
    areaSqKm: 7081,
  },
  {
    id: 'bauchi',
    name: 'Bauchi',
    region: 'North East',
    capital: 'Bauchi',
    lgas: ['Bauchi', 'Bogoro', 'Damban', 'Darazo', 'Dass', 'Gamawa', 'Ganjuwa', 'Giade', 'Itas/Gadau', 'Jama\'are', 'Katagum', 'Kirfi', 'Misau', 'Ningi', 'Shira', 'Tafawa Balewa', 'Toro', 'Warji', 'Zaki'],
    population: 7000000,
    areaSqKm: 45837,
  },
  {
    id: 'bayelsa',
    name: 'Bayelsa',
    region: 'South South',
    capital: 'Yenagoa',
    lgas: ['Brass', 'Ekeremor', 'Kolokuma/Opokuma', 'Nembe', 'Ogbia', 'Sagbama', 'Southern Ijaw', 'Yenagoa'],
    population: 2500000,
    areaSqKm: 10773,
  },
  {
    id: 'benue',
    name: 'Benue',
    region: 'North Central',
    capital: 'Makurdi',
    lgas: ['Ado', 'Agatu', 'Apa', 'Buruku', 'Gboko', 'Guma', 'Gwer East', 'Gwer West', 'Katsina-Ala', 'Konshisha', 'Kwande', 'Logo', 'Makurdi', 'Obi', 'Ogbadibo', 'Ohimini', 'Oju', 'Okpokwu', 'Otukpo', 'Tarka', 'Ukum', 'Ushongo', 'Vandeikya'],
    population: 6000000,
    areaSqKm: 34059,
  },
  {
    id: 'borno',
    name: 'Borno',
    region: 'North East',
    capital: 'Maiduguri',
    lgas: ['Abadam', 'Askira/Uba', 'Bama', 'Bayo', 'Biu', 'Chibok', 'Damboa', 'Dikwa', 'Gubio', 'Guzamala', 'Gwoza', 'Hawul', 'Jere', 'Kaga', 'Kala/Balge', 'Konduga', 'Kukawa', 'Kwaya Kusar', 'Mafa', 'Magumeri', 'Maiduguri', 'Marte', 'Mobbar', 'Monguno', 'Ngala', 'Nganzai', 'Shani'],
    population: 6000000,
    areaSqKm: 70898,
  },
  {
    id: 'cross-river',
    name: 'Cross River',
    region: 'South South',
    capital: 'Calabar',
    lgas: ['Abi', 'Akamkpa', 'Akpabuyo', 'Bakassi', 'Bekwarra', 'Biase', 'Boki', 'Calabar Municipal', 'Calabar South', 'Etung', 'Ikom', 'Obanliku', 'Obubra', 'Obudu', 'Odukpani', 'Ogoja', 'Yakuur', 'Yala'],
    population: 4000000,
    areaSqKm: 20156,
  },
  {
    id: 'ebonyi',
    name: 'Ebonyi',
    region: 'South East',
    capital: 'Abakaliki',
    lgas: ['Abakaliki', 'Afikpo North', 'Afikpo South', 'Ebonyi', 'Ezza North', 'Ezza South', 'Ikwo', 'Ishielu', 'Ivo', 'Izzi', 'Ohaozara', 'Ohaukwu', 'Onicha'],
    population: 3000000,
    areaSqKm: 5670,
  },
  {
    id: 'edo',
    name: 'Edo',
    region: 'South South',
    capital: 'Benin City',
    lgas: ['Akoko-Edo', 'Egor', 'Esan Central', 'Esan North-East', 'Esan South-East', 'Esan West', 'Etsako Central', 'Etsako East', 'Etsako West', 'Igueben', 'Ikpoba Okha', 'Oredo', 'Orhionmwon', 'Ovia North-East', 'Ovia South-West', 'Owan East', 'Owan West', 'Uhunmwonde'],
    population: 4500000,
    areaSqKm: 17802,
  },
  {
    id: 'ekiti',
    name: 'Ekiti',
    region: 'South West',
    capital: 'Ado-Ekiti',
    lgas: ['Ado Ekiti', 'Efon', 'Ekiti East', 'Ekiti South-West', 'Ekiti West', 'Emure', 'Gbonyin', 'Ido Osi', 'Ijero', 'Ikole', 'Ilejemeje', 'Irepodun/Ifelodun', 'Ise/Orun', 'Moba', 'Oye'],
    population: 3500000,
    areaSqKm: 6351,
  },
  {
    id: 'gombe',
    name: 'Gombe',
    region: 'North East',
    capital: 'Gombe',
    lgas: ['Akko', 'Balanga', 'Billiri', 'Dukku', 'Funakaye', 'Gombe', 'Kaltungo', 'Kwami', 'Nafada', 'Shongom', 'Yamaltu/Deba'],
    population: 3500000,
    areaSqKm: 18768,
  },
  {
    id: 'jigawa',
    name: 'Jigawa',
    region: 'North West',
    capital: 'Dutse',
    lgas: ['Auyo', 'Babura', 'Biriniwa', 'Birnin Kudu', 'Buji', 'Dutse', 'Gagarawa', 'Garki', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa', 'Hadejia', 'Jahun', 'Kafin Hausa', 'Kazaure', 'Kiri Kasama', 'Kiyawa', 'Kaugama', 'Maigatari', 'Malam Madori', 'Miga', 'Ringim', 'Roni', 'Sule Tankarkar', 'Taura', 'Yankwashi'],
    population: 6000000,
    areaSqKm: 23154,
  },
  {
    id: 'kebbi',
    name: 'Kebbi',
    region: 'North West',
    capital: 'Birnin Kebbi',
    lgas: ['Aleiro', 'Arewa Dandi', 'Argungu', 'Augie', 'Bagudo', 'Bunza', 'Dandi', 'Fakai', 'Gwandu', 'Jega', 'Kalgo', 'Koko/Besse', 'Maiyama', 'Ngaski', 'Sakaba', 'Shanga', 'Suru', 'Wasagu/Danko', 'Yauri', 'Zuru'],
    population: 4500000,
    areaSqKm: 36800,
  },
  {
    id: 'kwara',
    name: 'Kwara',
    region: 'North Central',
    capital: 'Ilorin',
    lgas: ['Asa', 'Baruten', 'Edu', 'Ekiti', 'Ifelodun', 'Ilorin East', 'Ilorin South', 'Ilorin West', 'Irepodun', 'Isin', 'Kaiama', 'Moro', 'Offa', 'Oke Ero', 'Oyun', 'Pategi'],
    population: 3500000,
    areaSqKm: 36825,
  },
  {
    id: 'nasarawa',
    name: 'Nasarawa',
    region: 'North Central',
    capital: 'Lafia',
    lgas: ['Akwanga', 'Awe', 'Doma', 'Karu', 'Keana', 'Keffi', 'Kokona', 'Lafia', 'Nasarawa', 'Nasarawa Egon', 'Obi', 'Toto', 'Wamba'],
    population: 2500000,
    areaSqKm: 27117,
  },
  {
    id: 'niger',
    name: 'Niger',
    region: 'North Central',
    capital: 'Minna',
    lgas: ['Agaie', 'Agwara', 'Bida', 'Borgu', 'Bosso', 'Chanchaga', 'Edati', 'Gbako', 'Gurara', 'Katcha', 'Kontagora', 'Lapai', 'Lavun', 'Magama', 'Mariga', 'Mashegu', 'Mokwa', 'Moya', 'Paikoro', 'Rafi', 'Rijau', 'Shiroro', 'Suleja', 'Tafa', 'Wushishi'],
    population: 6000000,
    areaSqKm: 76363,
  },
  {
    id: 'osun',
    name: 'Osun',
    region: 'South West',
    capital: 'Oshogbo',
    lgas: ['Atakunmosa East', 'Atakunmosa West', 'Aiyedaade', 'Aiyedire', 'Boluwaduro', 'Boripe', 'Ede North', 'Ede South', 'Ife Central', 'Ife East', 'Ife North', 'Ife South', 'Egbedore', 'Ejigbo', 'Ifedayo', 'Ifelodun', 'Ila', 'Ilesa East', 'Ilesa West', 'Irepodun', 'Irewole', 'Isokan', 'Iwo', 'Obokun', 'Odo Otin', 'Ola Oluwa', 'Olorunda', 'Oriade', 'Orolu', 'Osogbo'],
    population: 5000000,
    areaSqKm: 9251,
  },
  {
    id: 'plateau',
    name: 'Plateau',
    region: 'North Central',
    capital: 'Jos',
    lgas: ['Bokkos', 'Barkin Ladi', 'Bassa', 'Jos East', 'Jos North', 'Jos South', 'Kanam', 'Kanke', 'Langtang North', 'Langtang South', 'Mangu', 'Mikang', 'Pankshin', 'Qua\'an Pan', 'Riyom', 'Shendam', 'Wase'],
    population: 4500000,
    areaSqKm: 30913,
  },
  {
    id: 'sokoto',
    name: 'Sokoto',
    region: 'North West',
    capital: 'Sokoto',
    lgas: ['Binji', 'Bodinga', 'Dange Shuni', 'Gada', 'Goronyo', 'Gudu', 'Gwadabawa', 'Illela', 'Isa', 'Kebbe', 'Kware', 'Rabah', 'Sabon Birni', 'Shagari', 'Silame', 'Sokoto North', 'Sokoto South', 'Tambuwal', 'Tangaza', 'Tureta', 'Wamako', 'Wurno', 'Yabo'],
    population: 5500000,
    areaSqKm: 25973,
  },
  {
    id: 'taraba',
    name: 'Taraba',
    region: 'North East',
    capital: 'Jalingo',
    lgas: ['Ardo Kola', 'Bali', 'Donga', 'Gashaka', 'Gassol', 'Ibi', 'Jalingo', 'Karim Lamido', 'Kurmi', 'Lau', 'Sardauna', 'Takum', 'Ussa', 'Wukari', 'Yorro', 'Zing'],
    population: 3000000,
    areaSqKm: 54473,
  },
  {
    id: 'yobe',
    name: 'Yobe',
    region: 'North East',
    capital: 'Damaturu',
    lgas: ['Bade', 'Bursari', 'Fika', 'Fune', 'Geidam', 'Gujba', 'Gulani', 'Jakusko', 'Karasuwa', 'Machina', 'Nangere', 'Potiskum', 'Tarmuwa', 'Yunusari', 'Yusufari'],
    population: 3500000,
    areaSqKm: 45502,
  },
  {
    id: 'zamfara',
    name: 'Zamfara',
    region: 'North West',
    capital: 'Gusau',
    lgas: ['Anka', 'Bakura', 'Birnin Magaji/Kiyaw', 'Bukkuyum', 'Bungudu', 'Gummi', 'Gusau', 'Kankara', 'Kaura Namoda', 'Katsina', 'Maradun', 'Maru', 'Shinkafi', 'Talata Mafara', 'Chafe', 'Zurmi'],
    population: 5000000,
    areaSqKm: 39762,
  }
];

export const NIGERIAN_LANGUAGES_SEED: Partial<NigerianLanguage>[] = [
  {
    id: 'english',
    name: 'English',
    nativeName: 'English',
    greeting: 'Hello',
    description: 'Official language of Nigeria',
    speakersCount: 180000000,
    regions: ['All regions'],
    isMajor: true,
  },
  {
    id: 'hausa',
    name: 'Hausa',
    nativeName: 'Hausa',
    greeting: 'Sannu',
    description: 'Widely spoken in Northern Nigeria',
    speakersCount: 80000000,
    regions: ['North West', 'North East', 'North Central'],
    isMajor: true,
  },
  {
    id: 'yoruba',
    name: 'Yoruba',
    nativeName: 'Yorùbá',
    greeting: 'Ẹ káàsán',
    description: 'Spoken in South Western Nigeria',
    speakersCount: 45000000,
    regions: ['South West'],
    isMajor: true,
  },
  {
    id: 'igbo',
    name: 'Igbo',
    nativeName: 'Igbo',
    greeting: 'Nnọọ',
    description: 'Spoken in South Eastern Nigeria',
    speakersCount: 30000000,
    regions: ['South East'],
    isMajor: true,
  },
  {
    id: 'pidgin',
    name: 'Nigerian Pidgin',
    nativeName: 'Naija',
    greeting: 'How far?',
    description: 'Widely spoken informal language across Nigeria',
    speakersCount: 100000000,
    regions: ['All regions'],
    isMajor: false,
  },
  {
    id: 'fulfulde',
    name: 'Fulfulde',
    nativeName: 'Fulfulde',
    greeting: 'A salaam alaikum',
    description: 'Spoken by the Fulani people across Northern Nigeria',
    speakersCount: 15000000,
    regions: ['North West', 'North East', 'North Central'],
    isMajor: false,
  },
  {
    id: 'kanuri',
    name: 'Kanuri',
    nativeName: 'Kanuri',
    greeting: 'Salaam',
    description: 'Spoken in Borno and Yobe states',
    speakersCount: 5000000,
    regions: ['North East'],
    isMajor: false,
  },
  {
    id: 'ibibio',
    name: 'Ibibio',
    nativeName: 'Ibibio',
    greeting: 'Idem fo',
    description: 'Spoken in Akwa Ibom State',
    speakersCount: 4000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'tiv',
    name: 'Tiv',
    nativeName: 'Tiv',
    greeting: 'A va',
    description: 'Spoken in Benue State',
    speakersCount: 3000000,
    regions: ['North Central'],
    isMajor: false,
  },
  {
    id: 'ijaw',
    name: 'Ijaw',
    nativeName: 'Izon',
    greeting: 'Bote',
    description: 'Spoken in Bayelsa, Delta, and Rivers states',
    speakersCount: 2000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'edo',
    name: 'Edo',
    nativeName: 'Edo',
    greeting: 'Kóyo',
    description: 'Spoken in Edo State',
    speakersCount: 2000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'nupe',
    name: 'Nupe',
    nativeName: 'Nupe',
    greeting: 'Bàbá',
    description: 'Spoken in Niger and Kwara states',
    speakersCount: 1500000,
    regions: ['North Central'],
    isMajor: false,
  },
  {
    id: 'efik',
    name: 'Efik',
    nativeName: 'Efik',
    greeting: 'Idem fo',
    description: 'Spoken in Cross River and Akwa Ibom states',
    speakersCount: 2000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'annang',
    name: 'Annang',
    nativeName: 'Annang',
    greeting: 'Idem fo',
    description: 'Spoken in Akwa Ibom State',
    speakersCount: 1500000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'urhobo',
    name: 'Urhobo',
    nativeName: 'Urhobo',
    greeting: 'Mavo',
    description: 'Spoken in Delta State',
    speakersCount: 2000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'isoko',
    name: 'Isoko',
    nativeName: 'Isoko',
    greeting: 'Mavo',
    description: 'Spoken in Delta State',
    speakersCount: 1000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'itsekiri',
    name: 'Itsekiri',
    nativeName: 'Itsekiri',
    greeting: 'Mavo',
    description: 'Spoken in Delta State',
    speakersCount: 500000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio',
    name: 'Efik-Ibibio',
    nativeName: 'Efik-Ibibio',
    greeting: 'Idem fo',
    description: 'Language group spoken in Cross River and Akwa Ibom',
    speakersCount: 4000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'kalabari',
    name: 'Kalabari',
    nativeName: 'Kalabari',
    greeting: 'Bote',
    description: 'Spoken in Rivers State',
    speakersCount: 300000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'okrika',
    name: 'Okrika',
    nativeName: 'Okrika',
    greeting: 'Bote',
    description: 'Spoken in Rivers State',
    speakersCount: 200000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'ogoni',
    name: 'Ogoni',
    nativeName: 'Ogoni',
    greeting: 'Bote',
    description: 'Spoken in Rivers State',
    speakersCount: 500000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-efut',
    name: 'Efik-Efut',
    nativeName: 'Efik-Efut',
    greeting: 'Idem fo',
    description: 'Spoken in Cross River State',
    speakersCount: 100000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'boki',
    name: 'Boki',
    nativeName: 'Boki',
    greeting: 'Idem fo',
    description: 'Spoken in Cross River State',
    speakersCount: 200000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'yala',
    name: 'Yala',
    nativeName: 'Yala',
    greeting: 'Idem fo',
    description: 'Spoken in Cross River State',
    speakersCount: 150000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'bete',
    name: 'Bete',
    nativeName: 'Bete',
    greeting: 'Idem fo',
    description: 'Spoken in Cross River State',
    speakersCount: 100000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio-annang',
    name: 'Efik-Ibibio-Annang',
    nativeName: 'Efik-Ibibio-Annang',
    greeting: 'Idem fo',
    description: 'Language cluster spoken in South South region',
    speakersCount: 6000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio-annang-oron',
    name: 'Efik-Ibibio-Annang-Oron',
    nativeName: 'Efik-Ibibio-Annang-Oron',
    greeting: 'Idem fo',
    description: 'Language cluster including Oron dialect',
    speakersCount: 7000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio-annang-oron-efut',
    name: 'Efik-Ibibio-Annang-Oron-Efut',
    nativeName: 'Efik-Ibibio-Annang-Oron-Efut',
    greeting: 'Idem fo',
    description: 'Complete language cluster of South South region',
    speakersCount: 8000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio-annang-oron-efut-boki',
    name: 'Efik-Ibibio-Annang-Oron-Efut-Boki',
    nativeName: 'Efik-Ibibio-Annang-Oron-Efut-Boki',
    greeting: 'Idem fo',
    description: 'Extended language cluster including Boki',
    speakersCount: 8500000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio-annang-oron-efut-boki-yala',
    name: 'Efik-Ibibio-Annang-Oron-Efut-Boki-Yala',
    nativeName: 'Efik-Ibibio-Annang-Oron-Efut-Boki-Yala',
    greeting: 'Idem fo',
    description: 'Complete South South language cluster',
    speakersCount: 9000000,
    regions: ['South South'],
    isMajor: false,
  },
  {
    id: 'efik-ibibio-annang-oron-efut-boki-yala-bete',
    name: 'Efik-Ibibio-Annang-Oron-Efut-Boki-Yala-Bete',
    nativeName: 'Efik-Ibibio-Annang-Oron-Efut-Boki-Yala-Bete',
    greeting: 'Idem fo',
    description: 'Complete South South language cluster with all dialects',
    speakersCount: 9500000,
    regions: ['South South'],
    isMajor: false,
  }
];

export const CULTURAL_BACKGROUNDS_SEED: Partial<CulturalBackground>[] = [
  {
    id: 'yoruba',
    name: 'Yoruba',
    region: 'South West',
    description: 'One of the largest ethnic groups in West Africa',
    traditions: {
      festivals: ['Olojo Festival', 'Eyo Festival', 'Osun-Osogbo', 'Eyo Festival'],
      cuisine: ['Amala', 'Ewedu', 'Egusi', 'Jollof Rice', 'Pounded Yam'],
      music: ['Juju', 'Fuji', 'Afrobeat', 'Apala'],
      greetings: ['Ẹ káàsán', 'Ẹ káàbọ̀', 'Ẹ kú ìrọ̀lẹ́'],
      values: ['Respect for elders', 'Community spirit', 'Hard work', 'Education']
    },
    populationEstimate: 45000000,
  },
  {
    id: 'igbo',
    name: 'Igbo',
    region: 'South East',
    description: 'Indigenous people of southeastern Nigeria',
    traditions: {
      festivals: ['New Yam Festival', 'Iwa Akwa', 'Mmanwu Festival', 'Ofala Festival'],
      cuisine: ['Abacha', 'Ofe Nsala', 'Nkwobi', 'Bitterleaf Soup', 'Fufu'],
      music: ['Highlife', 'Igbo Traditional', 'Gospel'],
      greetings: ['Nnọọ', 'Kedu', 'Biko'],
      values: ['Enterprise', 'Education', 'Respect', 'Hard work']
    },
    populationEstimate: 40000000,
  },
  {
    id: 'hausa',
    name: 'Hausa',
    region: 'North West',
    description: 'Largest ethnic group in West Africa',
    traditions: {
      festivals: ['Durbar', 'Sallah', 'Eid al-Fitr', 'Eid al-Adha'],
      cuisine: ['Suya', 'Tuwo Shinkafa', 'Miyan Kuka', 'Fura da Nono'],
      music: ['Hausa traditional music', 'Quranic recitation'],
      greetings: ['Sannu', 'Barka', 'Ina kwana'],
      values: ['Hospitality', 'Respect', 'Community', 'Religion']
    },
    populationEstimate: 80000000,
  },
  {
    id: 'fulani',
    name: 'Fulani',
    region: 'North West',
    description: 'Nomadic and semi-nomadic pastoralist people',
    traditions: {
      festivals: ['Sharo Festival', 'Gerewol Festival'],
      cuisine: ['Fura da Nono', 'Miyan Taushe', 'Tuwo Shinkafa'],
      music: ['Fulani traditional music', 'Flute music'],
      greetings: ['A salaam alaikum', 'Jam na'],
      values: ['Hospitality', 'Cattle rearing', 'Nomadic lifestyle', 'Community']
    },
    populationEstimate: 15000000,
  },
  {
    id: 'ijaw',
    name: 'Ijaw',
    region: 'South South',
    description: 'Indigenous people of the Niger Delta region',
    traditions: {
      festivals: ['Ijaw Festival', 'Okrika Festival', 'Bonny Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Fish', 'Plantain'],
      music: ['Ijaw traditional music', 'Drum music'],
      greetings: ['Bote', 'Kedu'],
      values: ['Fishing', 'Community', 'Water culture', 'Respect for nature']
    },
    populationEstimate: 2000000,
  },
  {
    id: 'edo',
    name: 'Edo',
    region: 'South South',
    description: 'Indigenous people of Edo State, known for the Benin Kingdom',
    traditions: {
      festivals: ['Igue Festival', 'Eho Festival', 'Ovia Festival'],
      cuisine: ['Bini Soup', 'Owo Soup', 'Plantain Porridge'],
      music: ['Edo traditional music', 'Drum music'],
      greetings: ['Kóyo', 'Óbó'],
      values: ['Royal heritage', 'Art and craft', 'Respect for tradition', 'Community']
    },
    populationEstimate: 2000000,
  },
  {
    id: 'tiv',
    name: 'Tiv',
    region: 'North Central',
    description: 'Indigenous people of Benue State',
    traditions: {
      festivals: ['Swange Festival', 'Kwagh-hir Festival'],
      cuisine: ['Tiv Soup', 'Pounded Yam', 'Rice'],
      music: ['Tiv traditional music', 'Swange dance'],
      greetings: ['A va', 'U yô'],
      values: ['Agriculture', 'Community', 'Respect', 'Hard work']
    },
    populationEstimate: 3000000,
  },
  {
    id: 'nupe',
    name: 'Nupe',
    region: 'North Central',
    description: 'Indigenous people of Niger and Kwara states',
    traditions: {
      festivals: ['Nupe Festival', 'Etsu Festival'],
      cuisine: ['Nupe Soup', 'Tuwo', 'Rice'],
      music: ['Nupe traditional music', 'Drum music'],
      greetings: ['Bàbá', 'Kóyo'],
      values: ['Farming', 'Fishing', 'Community', 'Respect']
    },
    populationEstimate: 1500000,
  },
  {
    id: 'efik',
    name: 'Efik',
    region: 'South South',
    description: 'Indigenous people of Cross River and Akwa Ibom states',
    traditions: {
      festivals: ['Ekpe Festival', 'Ekong Festival', 'Nkwa Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 2000000,
  },
  {
    id: 'ibibio',
    name: 'Ibibio',
    region: 'South South',
    description: 'Indigenous people of Akwa Ibom State',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Ibibio traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 4000000,
  },
  {
    id: 'annang',
    name: 'Annang',
    region: 'South South',
    description: 'Indigenous people of Akwa Ibom State',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Annang traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 1500000,
  },
  {
    id: 'urhobo',
    name: 'Urhobo',
    region: 'South South',
    description: 'Indigenous people of Delta State',
    traditions: {
      festivals: ['Urhobo Festival', 'Ekpe Festival', 'Nkwa Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Plantain'],
      music: ['Urhobo traditional music', 'Drum music'],
      greetings: ['Mavo', 'Kedu'],
      values: ['Farming', 'Fishing', 'Community', 'Respect']
    },
    populationEstimate: 2000000,
  },
  {
    id: 'isoko',
    name: 'Isoko',
    region: 'South South',
    description: 'Indigenous people of Delta State',
    traditions: {
      festivals: ['Isoko Festival', 'Ekpe Festival', 'Nkwa Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Plantain'],
      music: ['Isoko traditional music', 'Drum music'],
      greetings: ['Mavo', 'Kedu'],
      values: ['Farming', 'Fishing', 'Community', 'Respect']
    },
    populationEstimate: 1000000,
  },
  {
    id: 'itsekiri',
    name: 'Itsekiri',
    region: 'South South',
    description: 'Indigenous people of Delta State',
    traditions: {
      festivals: ['Itsekiri Festival', 'Ekpe Festival', 'Nkwa Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Plantain'],
      music: ['Itsekiri traditional music', 'Drum music'],
      greetings: ['Mavo', 'Kedu'],
      values: ['Farming', 'Fishing', 'Community', 'Respect']
    },
    populationEstimate: 500000,
  },
  {
    id: 'kalabari',
    name: 'Kalabari',
    region: 'South South',
    description: 'Indigenous people of Rivers State',
    traditions: {
      festivals: ['Kalabari Festival', 'Ekpe Festival', 'Nkwa Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Plantain'],
      music: ['Kalabari traditional music', 'Drum music'],
      greetings: ['Bote', 'Kedu'],
      values: ['Fishing', 'Community', 'Water culture', 'Respect for nature']
    },
    populationEstimate: 300000,
  },
  {
    id: 'okrika',
    name: 'Okrika',
    region: 'South South',
    description: 'Indigenous people of Rivers State',
    traditions: {
      festivals: ['Okrika Festival', 'Ekpe Festival', 'Nkwa Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Plantain'],
      music: ['Okrika traditional music', 'Drum music'],
      greetings: ['Bote', 'Kedu'],
      values: ['Fishing', 'Community', 'Water culture', 'Respect for nature']
    },
    populationEstimate: 200000,
  },
  {
    id: 'ogoni',
    name: 'Ogoni',
    region: 'South South',
    description: 'Indigenous people of Rivers State',
    traditions: {
      festivals: ['Ogoni Festival', 'Ekpe Festival', 'Nkwa Festival'],
      cuisine: ['Banga Soup', 'Pepper Soup', 'Plantain'],
      music: ['Ogoni traditional music', 'Drum music'],
      greetings: ['Bote', 'Kedu'],
      values: ['Fishing', 'Community', 'Water culture', 'Respect for nature']
    },
    populationEstimate: 500000,
  },
  {
    id: 'efik-ibibio-annang',
    name: 'Efik-Ibibio-Annang',
    region: 'South South',
    description: 'Language cluster of South South region',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik-Ibibio-Annang traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 6000000,
  },
  {
    id: 'efik-ibibio-annang-oron',
    name: 'Efik-Ibibio-Annang-Oron',
    region: 'South South',
    description: 'Language cluster including Oron dialect',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik-Ibibio-Annang-Oron traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 7000000,
  },
  {
    id: 'efik-ibibio-annang-oron-efut',
    name: 'Efik-Ibibio-Annang-Oron-Efut',
    region: 'South South',
    description: 'Complete language cluster of South South region',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik-Ibibio-Annang-Oron-Efut traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 8000000,
  },
  {
    id: 'efik-ibibio-annang-oron-efut-boki',
    name: 'Efik-Ibibio-Annang-Oron-Efut-Boki',
    region: 'South South',
    description: 'Extended language cluster including Boki',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik-Ibibio-Annang-Oron-Efut-Boki traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 8500000,
  },
  {
    id: 'efik-ibibio-annang-oron-efut-boki-yala',
    name: 'Efik-Ibibio-Annang-Oron-Efut-Boki-Yala',
    region: 'South South',
    description: 'Complete South South language cluster',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik-Ibibio-Annang-Oron-Efut-Boki-Yala traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 9000000,
  },
  {
    id: 'efik-ibibio-annang-oron-efut-boki-yala-bete',
    name: 'Efik-Ibibio-Annang-Oron-Efut-Boki-Yala-Bete',
    region: 'South South',
    description: 'Complete South South language cluster with all dialects',
    traditions: {
      festivals: ['Ekong Festival', 'Nkwa Festival', 'Ekpe Festival'],
      cuisine: ['Edikang Ikong', 'Afang Soup', 'Fisherman Soup'],
      music: ['Efik-Ibibio-Annang-Oron-Efut-Boki-Yala-Bete traditional music', 'Ekpe music'],
      greetings: ['Idem fo', 'Kedu'],
      values: ['Hospitality', 'Trade', 'Education', 'Community']
    },
    populationEstimate: 9500000,
  }
];

export const PROFESSIONAL_CATEGORIES_SEED: Partial<ProfessionalCategory>[] = [
  {
    category: 'Technology & Engineering',
    titles: [
      'Software Engineer',
      'Data Scientist',
      'Network Engineer',
      'IT Support Specialist',
      'Web Developer',
      'Mobile Developer',
      'DevOps Engineer',
      'Cybersecurity Specialist',
      'Product Manager',
      'UI/UX Designer',
      'System Administrator',
      'Database Administrator',
      'Cloud Engineer',
      'AI/ML Engineer',
      'Blockchain Developer'
    ],
    icon: 'laptop-code',
    displayOrder: 1,
  },
  {
    category: 'Healthcare',
    titles: [
      'Medical Doctor',
      'Nurse',
      'Pharmacist',
      'Dentist',
      'Physiotherapist',
      'Lab Technician',
      'Radiographer',
      'Optometrist',
      'Health Administrator',
      'Medical Laboratory Scientist',
      'Community Health Worker',
      'Mental Health Counselor',
      'Veterinarian',
      'Dental Hygienist',
      'Health Educator'
    ],
    icon: 'hospital',
    displayOrder: 2,
  },
  {
    category: 'Education',
    titles: [
      'Teacher',
      'Lecturer',
      'Principal',
      'Education Administrator',
      'Tutor',
      'Librarian',
      'Educational Consultant',
      'Curriculum Developer',
      'School Counselor',
      'Research Assistant',
      'Academic Advisor',
      'Training Coordinator',
      'Educational Technology Specialist',
      'Student Affairs Officer',
      'Education Policy Analyst'
    ],
    icon: 'graduation-cap',
    displayOrder: 3,
  },
  {
    category: 'Business & Finance',
    titles: [
      'Accountant',
      'Financial Analyst',
      'Banker',
      'Investment Advisor',
      'Business Analyst',
      'Project Manager',
      'Human Resources Manager',
      'Marketing Manager',
      'Sales Representative',
      'Operations Manager',
      'Business Development Manager',
      'Auditor',
      'Tax Consultant',
      'Insurance Agent',
      'Real Estate Agent'
    ],
    icon: 'briefcase',
    displayOrder: 4,
  },
  {
    category: 'Legal',
    titles: [
      'Lawyer',
      'Judge',
      'Legal Advisor',
      'Paralegal',
      'Court Clerk',
      'Legal Secretary',
      'Compliance Officer',
      'Corporate Counsel',
      'Public Defender',
      'Prosecutor',
      'Legal Researcher',
      'Arbitrator',
      'Mediator',
      'Notary Public',
      'Legal Consultant'
    ],
    icon: 'gavel',
    displayOrder: 5,
  },
  {
    category: 'Creative Arts',
    titles: [
      'Graphic Designer',
      'Photographer',
      'Videographer',
      'Musician',
      'Artist',
      'Writer',
      'Content Creator',
      'Fashion Designer',
      'Interior Designer',
      'Architect',
      'Animator',
      'Film Director',
      'Sound Engineer',
      'Event Planner',
      'Creative Director'
    ],
    icon: 'palette',
    displayOrder: 6,
  },
  {
    category: 'Trades & Services',
    titles: [
      'Electrician',
      'Plumber',
      'Carpenter',
      'Mechanic',
      'Welder',
      'Painter',
      'Mason',
      'Driver',
      'Security Guard',
      'Cleaner',
      'Gardener',
      'Cook',
      'Waiter',
      'Hairdresser',
      'Tailor'
    ],
    icon: 'tools',
    displayOrder: 7,
  },
  {
    category: 'Agriculture',
    titles: [
      'Farmer',
      'Agricultural Engineer',
      'Veterinarian',
      'Agricultural Extension Worker',
      'Crop Specialist',
      'Livestock Manager',
      'Agricultural Consultant',
      'Food Scientist',
      'Agricultural Economist',
      'Farm Manager',
      'Agricultural Researcher',
      'Seed Specialist',
      'Pest Control Specialist',
      'Agricultural Sales Representative',
      'Rural Development Officer'
    ],
    icon: 'seedling',
    displayOrder: 8,
  },
  {
    category: 'Transportation',
    titles: [
      'Pilot',
      'Driver',
      'Mechanic',
      'Logistics Coordinator',
      'Transport Manager',
      'Air Traffic Controller',
      'Marine Engineer',
      'Railway Engineer',
      'Fleet Manager',
      'Dispatch Coordinator',
      'Transportation Planner',
      'Vehicle Inspector',
      'Cargo Handler',
      'Transportation Analyst',
      'Route Planner'
    ],
    icon: 'truck',
    displayOrder: 9,
  },
  {
    category: 'Government & Public Service',
    titles: [
      'Civil Servant',
      'Politician',
      'Public Administrator',
      'Policy Analyst',
      'Government Relations Officer',
      'Public Affairs Officer',
      'Community Development Officer',
      'Social Worker',
      'Public Health Officer',
      'Environmental Officer',
      'Urban Planner',
      'Diplomat',
      'Customs Officer',
      'Immigration Officer',
      'Tax Officer'
    ],
    icon: 'building',
    displayOrder: 10,
  },
  {
    category: 'Media & Communications',
    titles: [
      'Journalist',
      'News Anchor',
      'Radio Presenter',
      'TV Producer',
      'Content Writer',
      'Social Media Manager',
      'Public Relations Officer',
      'Marketing Communications Specialist',
      'Copywriter',
      'Editor',
      'Photographer',
      'Videographer',
      'Podcast Host',
      'Media Consultant',
      'Communications Manager'
    ],
    icon: 'microphone',
    displayOrder: 11,
  },
  {
    category: 'Sports & Fitness',
    titles: [
      'Professional Athlete',
      'Sports Coach',
      'Fitness Trainer',
      'Sports Administrator',
      'Referee',
      'Sports Journalist',
      'Sports Medicine Doctor',
      'Physical Therapist',
      'Sports Nutritionist',
      'Sports Psychologist',
      'Sports Equipment Manager',
      'Sports Event Coordinator',
      'Personal Trainer',
      'Yoga Instructor',
      'Sports Analyst'
    ],
    icon: 'trophy',
    displayOrder: 12,
  },
  {
    category: 'Hospitality & Tourism',
    titles: [
      'Hotel Manager',
      'Chef',
      'Restaurant Manager',
      'Tour Guide',
      'Travel Agent',
      'Event Coordinator',
      'Catering Manager',
      'Concierge',
      'Housekeeping Manager',
      'Food Service Manager',
      'Tourism Officer',
      'Resort Manager',
      'Banquet Manager',
      'Guest Relations Manager',
      'Travel Consultant'
    ],
    icon: 'utensils',
    displayOrder: 13,
  },
  {
    category: 'Real Estate & Construction',
    titles: [
      'Real Estate Agent',
      'Property Manager',
      'Architect',
      'Civil Engineer',
      'Construction Manager',
      'Quantity Surveyor',
      'Urban Planner',
      'Interior Designer',
      'Land Surveyor',
      'Building Inspector',
      'Project Manager',
      'Real Estate Developer',
      'Property Valuer',
      'Construction Supervisor',
      'Building Contractor'
    ],
    icon: 'home',
    displayOrder: 14,
  },
  {
    category: 'Energy & Utilities',
    titles: [
      'Electrical Engineer',
      'Power Plant Operator',
      'Energy Consultant',
      'Oil & Gas Engineer',
      'Renewable Energy Specialist',
      'Utility Manager',
      'Power Systems Engineer',
      'Energy Auditor',
      'Petroleum Engineer',
      'Solar Installer',
      'Wind Energy Technician',
      'Nuclear Engineer',
      'Energy Policy Analyst',
      'Power Distribution Manager',
      'Energy Efficiency Specialist'
    ],
    icon: 'zap',
    displayOrder: 15,
  },
  {
    category: 'Manufacturing & Production',
    titles: [
      'Production Manager',
      'Quality Control Inspector',
      'Manufacturing Engineer',
      'Industrial Designer',
      'Production Supervisor',
      'Machine Operator',
      'Assembly Line Worker',
      'Quality Assurance Manager',
      'Process Engineer',
      'Maintenance Technician',
      'Supply Chain Manager',
      'Operations Manager',
      'Safety Officer',
      'Production Planner',
      'Manufacturing Consultant'
    ],
    icon: 'cog',
    displayOrder: 16,
  },
  {
    category: 'Retail & Sales',
    titles: [
      'Sales Manager',
      'Retail Manager',
      'Sales Representative',
      'Store Manager',
      'Customer Service Representative',
      'Sales Director',
      'Account Manager',
      'Business Development Manager',
      'Sales Analyst',
      'Retail Buyer',
      'Merchandiser',
      'Sales Coordinator',
      'Territory Manager',
      'Sales Trainer',
      'Customer Success Manager'
    ],
    icon: 'shopping-cart',
    displayOrder: 17,
  },
  {
    category: 'Security & Safety',
    titles: [
      'Security Guard',
      'Police Officer',
      'Security Manager',
      'Safety Officer',
      'Firefighter',
      'Security Consultant',
      'Loss Prevention Specialist',
      'Emergency Response Coordinator',
      'Security Analyst',
      'Safety Inspector',
      'Security Systems Technician',
      'Risk Assessment Specialist',
      'Security Trainer',
      'Crisis Management Specialist',
      'Security Operations Manager'
    ],
    icon: 'shield',
    displayOrder: 18,
  },
  {
    category: 'Entertainment & Arts',
    titles: [
      'Actor',
      'Musician',
      'Dancer',
      'Comedian',
      'Event Planner',
      'Art Director',
      'Costume Designer',
      'Makeup Artist',
      'Sound Engineer',
      'Lighting Technician',
      'Stage Manager',
      'Producer',
      'Director',
      'Choreographer',
      'Entertainment Manager'
    ],
    icon: 'music',
    displayOrder: 19,
  },
  {
    category: 'Non-Profit & Social Work',
    titles: [
      'Social Worker',
      'Community Organizer',
      'Fundraising Manager',
      'Program Coordinator',
      'Volunteer Coordinator',
      'Grant Writer',
      'Advocacy Specialist',
      'Community Outreach Worker',
      'Social Services Manager',
      'Youth Worker',
      'Family Counselor',
      'Community Development Specialist',
      'Non-Profit Manager',
      'Social Impact Analyst',
      'Community Health Worker'
    ],
    icon: 'heart',
    displayOrder: 20,
  }
];
