import { Achievement, Badge, AchievementCategory, AchievementRarity, BadgeType } from '../entities';

export const ACHIEVEMENT_SEEDS: Partial<Achievement>[] = [
  {
    name: 'New Neighbor',
    description: 'Welcome to the community! Complete your profile to get started.',
    icon: 'home-heart',
    color: '#00A651',
    category: AchievementCategory.COMMUNITY,
    points: 50,
    rarity: AchievementRarity.COMMON,
    requirements: {
      type: 'profile_completion',
      count: 1,
      description: 'Complete your profile information',
    },
  },
  {
    name: 'Safety First',
    description: 'Report a safety concern to help keep your community safe.',
    icon: 'shield-check',
    color: '#FF6B35',
    category: AchievementCategory.SAFETY,
    points: 100,
    rarity: AchievementRarity.UNCOMMON,
    requirements: {
      type: 'safety_report',
      count: 1,
      description: 'Report a safety concern',
    },
  },
  {
    name: 'Social Butterfly',
    description: 'Make your first post and start connecting with neighbors.',
    icon: 'chat-heart',
    color: '#FFD23F',
    category: AchievementCategory.SOCIAL,
    points: 25,
    rarity: AchievementRarity.COMMON,
    requirements: {
      type: 'post_created',
      count: 1,
      description: 'Create your first post',
    },
  },
  {
    name: 'Event Organizer',
    description: 'Create your first community event.',
    icon: 'calendar-star',
    color: '#8B5CF6',
    category: AchievementCategory.EVENTS,
    points: 150,
    rarity: AchievementRarity.UNCOMMON,
    requirements: {
      type: 'event_created',
      count: 1,
      description: 'Create a community event',
    },
  },
  {
    name: 'Event Attendee',
    description: 'Attend your first community event.',
    icon: 'calendar-check',
    color: '#10B981',
    category: AchievementCategory.EVENTS,
    points: 75,
    rarity: AchievementRarity.COMMON,
    requirements: {
      type: 'event_attended',
      count: 1,
      description: 'Attend a community event',
    },
  },
  {
    name: 'Marketplace Seller',
    description: 'List your first item for sale in the marketplace.',
    icon: 'store',
    color: '#F59E0B',
    category: AchievementCategory.BUSINESS,
    points: 100,
    rarity: AchievementRarity.COMMON,
    requirements: {
      type: 'listing_created',
      count: 1,
      description: 'Create your first marketplace listing',
    },
  },
  {
    name: 'Helpful Neighbor',
    description: 'Respond to a help request from a neighbor.',
    icon: 'hand-heart',
    color: '#EF4444',
    category: AchievementCategory.COMMUNITY,
    points: 200,
    rarity: AchievementRarity.RARE,
    requirements: {
      type: 'help_provided',
      count: 1,
      description: 'Help a neighbor in need',
    },
  },
  {
    name: 'Community Builder',
    description: 'Create 10 posts to build community engagement.',
    icon: 'account-group',
    color: '#8B5CF6',
    category: AchievementCategory.LEADERSHIP,
    points: 500,
    rarity: AchievementRarity.EPIC,
    requirements: {
      type: 'post_created',
      count: 10,
      description: 'Create 10 community posts',
    },
  },
  {
    name: 'Safety Champion',
    description: 'Report 5 safety concerns to keep the community safe.',
    icon: 'shield-star',
    color: '#DC2626',
    category: AchievementCategory.SAFETY,
    points: 750,
    rarity: AchievementRarity.EPIC,
    requirements: {
      type: 'safety_report',
      count: 5,
      description: 'Report 5 safety concerns',
    },
  },
  {
    name: 'Event Master',
    description: 'Organize 5 successful community events.',
    icon: 'party-popper',
    color: '#7C3AED',
    category: AchievementCategory.EVENTS,
    points: 1000,
    rarity: AchievementRarity.LEGENDARY,
    requirements: {
      type: 'event_created',
      count: 5,
      description: 'Organize 5 community events',
    },
  },
  {
    name: 'Business Owner',
    description: 'Successfully sell 10 items in the marketplace.',
    icon: 'trophy',
    color: '#F59E0B',
    category: AchievementCategory.BUSINESS,
    points: 800,
    rarity: AchievementRarity.EPIC,
    requirements: {
      type: 'listing_sold',
      count: 10,
      description: 'Sell 10 marketplace items',
    },
  },
  {
    name: 'Community Legend',
    description: 'Reach level 10 and become a community legend.',
    icon: 'crown',
    color: '#FFD700',
    category: AchievementCategory.LEADERSHIP,
    points: 2000,
    rarity: AchievementRarity.LEGENDARY,
    requirements: {
      type: 'level_reached',
      count: 10,
      description: 'Reach level 10',
    },
  },
  {
    name: 'Daily Active',
    description: 'Log in for 7 consecutive days.',
    icon: 'calendar-today',
    color: '#06B6D4',
    category: AchievementCategory.COMMUNITY,
    points: 300,
    rarity: AchievementRarity.RARE,
    requirements: {
      type: 'daily_login',
      count: 7,
      description: 'Log in for 7 consecutive days',
    },
  },
];

export const BADGE_SEEDS: Partial<Badge>[] = [
  {
    name: 'Verified Neighbor',
    description: 'Phone number and address verified',
    icon: 'check-decagram',
    color: '#00A651',
    type: BadgeType.VERIFIED,
    requirementsText: 'Complete phone and address verification',
    requirementsConfig: {
      type: 'verification',
      requirements: ['phone_verified', 'address_verified'],
    },
  },
  {
    name: 'Safety Guardian',
    description: 'Dedicated to community safety',
    icon: 'shield-check',
    color: '#FF6B35',
    type: BadgeType.SAFETY,
    requirementsText: 'Report 3 safety concerns',
    requirementsConfig: {
      type: 'safety_reports',
      count: 3,
    },
  },
  {
    name: 'Event Host',
    description: 'Community event organizer',
    icon: 'calendar-star',
    color: '#8B5CF6',
    type: BadgeType.LEADERSHIP,
    requirementsText: 'Organize 2 community events',
    requirementsConfig: {
      type: 'events_organized',
      count: 2,
    },
  },
  {
    name: 'Helpful Hand',
    description: 'Always ready to help neighbors',
    icon: 'hand-heart',
    color: '#EF4444',
    type: BadgeType.CONTRIBUTION,
    requirementsText: 'Help 5 neighbors with requests',
    requirementsConfig: {
      type: 'help_provided',
      count: 5,
    },
  },
  {
    name: 'Social Connector',
    description: 'Active in community discussions',
    icon: 'chat-heart',
    color: '#FFD23F',
    type: BadgeType.SOCIAL,
    requirementsText: 'Create 20 posts and 50 comments',
    requirementsConfig: {
      type: 'social_activity',
      posts: 20,
      comments: 50,
    },
  },
  {
    name: 'Marketplace Pro',
    description: 'Successful marketplace participant',
    icon: 'store',
    color: '#F59E0B',
    type: BadgeType.BUSINESS,
    requirementsText: 'Sell 5 items and maintain 4.5+ rating',
    requirementsConfig: {
      type: 'marketplace_success',
      items_sold: 5,
      min_rating: 4.5,
    },
  },
  {
    name: 'Community Champion',
    description: 'Top contributor to community growth',
    icon: 'trophy',
    color: '#FFD700',
    type: BadgeType.LEADERSHIP,
    requirementsText: 'Reach level 8 and have 100+ total points',
    requirementsConfig: {
      type: 'leadership',
      min_level: 8,
      min_points: 100,
    },
  },
  {
    name: 'Estate Legend',
    description: 'Ultimate community recognition',
    icon: 'crown',
    color: '#8B5CF6',
    type: BadgeType.LEADERSHIP,
    requirementsText: 'Reach level 10 and earn all other badges',
    requirementsConfig: {
      type: 'legendary',
      min_level: 10,
      requires_all_badges: true,
    },
  },
];
